### ISSUE TITLE
[GLPI 9.1] upgrade of plugin does not show the new version

### ISSUE THREAD

**Issue by sebfun** [InfotelGLPI/consumables#11]
Hello 

I try to upgrade from 1.2.0 to 1.2.1. I turn off the plugin on configuration menu.
 I copy all files. I reactivate the plugin, it does not say "update" but only "activate" and shows the 1.2.0 version instead of 1.2.1

**Comment by amma35** [comment]
Hello,

Indeed, there is a bug in the version number.
This version contains minor changes, there is no problem for the functioning of the plugin if you do not carry out the update.

**Comment by sebfun** [comment]
ok thanks
