### ISSUE TITLE
Error message and notification not work

### ISSUE THREAD

**Issue by mrspam** [InfotelGLPI/consumables#12]
Hi everybody !

- The version of the plugin : 1.2.1
- The version of your GLPI : 9.1.2

Notification not work (notification active in configuration) and error message (in red) when validate a consumable request (validate or not same error, you can see the print screen).

![image](https://cloud.githubusercontent.com/assets/26159277/23541859/6688163c-0003-11e7-9b56-689a197eb451.jpg)

No error in php-errors.log and sql-errors.log in /glpi/files/_log

Any advice please ?

Thanks ! =)

**Comment by mrspam** [comment]
An other test with an other consumable, I have this error in php-error.log when I make a consumable request.

*** PHP Notice(8): Undefined index: order_ref
  Backtrace :
  plugins/consumables/inc/field.class.php:88
  :                                                  PluginConsumablesField::postAddConsumable()
  inc/plugin.class.php:1125                          call_user_func()
  inc/commondbtm.class.php:885                       Plugin::doHook()
  front/consumableitem.form.php:52                   CommonDBTM->add()

Always no notification about request and validation request.

**Comment by amma35** [comment]
Yes the alert in red is an information of the heart of GLPI.

How is your notification configured (recipients, activation, notification template, ..) ? 

We noticed the php error

**Comment by amma35** [comment]
if there is still a problem with notifications, can you open a new issue?
