### ISSUE TITLE
No more than 5  consumables ?

### ISSUE THREAD

**Issue by Leteint** [InfotelGLPI/consumables#13]
Dear Team,

- Version of the plugin : 1.2.1 
- Version of GLPI. : 9.1.2
From admin menu, in 'Plug-In / Demandes de consommables' : 
- once I have set 5 consumables from a category : I can't had more.

The number is set to 'Nombre *	Aucun consommable' but consumables are availlables 

Thanks
![demandedeconsommables](https://cloud.githubusercontent.com/assets/1765352/25736789/5b1b2206-3174-11e7-8f29-5f457b4e942f.png)

JB

**Comment by amma35** [comment]
Do you have errors in the files glpi/_logs/php-errors.log and sql-errors.log ? 

How many consumables are available?

**Comment by Leteint** [comment]
Dear Team, 
I can't see anymore this problem ; nowadays I use this tool in my society ; Thanks a lot

Best regards
