### ISSUE TITLE
Notification of "Consumables Request Validation" template with issues in tags

### ISSUE THREAD

**Issue by George2x** [InfotelGLPI/consumables#14]
- The version of the plugin: 1.2.0
- The version of your GLPI: 9.1.2 & 9.1.3
- The steps to reproduce your issue:

Refuse or approve materials, I received notification with empty value for ##consumablerequest.validator##, using the template Consumables Request Validation (first img). Also, only for refuse option I received the notification with the status "Waiting for approval" and must be Rejected or similar. Using the for each, it duplicates the tags with empty fields (2nd img).

![approved materials](https://user-images.githubusercontent.com/26604752/26995819-284c0cfe-4d2c-11e7-947b-07e9b3448449.JPG)
![rejected materials](https://user-images.githubusercontent.com/26604752/26995804-197e46a6-4d2c-11e7-93da-bf9a4da46bc7.JPG)

The template is:

A continuación el resultado de aprobación de material(es):

##FOREACHconsumabledatas##
##lang.consumablerequest.requester## : ##consumablerequest.requester##
##lang.consumablerequest.validator## : ##consumablerequest.validator##
##lang.consumablerequest.consumabletype## : ##consumablerequest.consumabletype##
##lang.consumablerequest.consumable## : ##consumablerequest.consumable##
##lang.consumablerequest.number## : ##consumablerequest.number##
##lang.consumablerequest.request_date## : ##consumablerequest.request_date##
##lang.consumablerequest.status## : ##consumablerequest.status##
##lang.consumable.entity## :##consumable.entity##
##ENDFOREACHconsumabledatas##

##lang.consumablerequest.comment## : ##consumablerequest.comment##

**Comment by amma35** [comment]
Have you tested with the version 1.2.1 plugin at first?

**Comment by George2x** [comment]
Not yet but I'll do right now and I'll let you know. Thanks for your help and this excellent work in the plugin.

**Comment by George2x** [comment]
I update to 1.2.1 the plugin and did the test, but problem continues as you could see in the screenshot attached.

![image](https://user-images.githubusercontent.com/26604752/27038222-94308c98-4f47-11e7-905a-c9932f1186ab.png)

**Comment by amma35** [comment]
I have reproduced your bug.

Can you test by replacing the file validation.class.php (https://github.com/InfotelGLPI/consumables/blob/master/inc/validation.class.php) in glpi/plugins/consumables/inc/ ?

**Comment by George2x** [comment]
Thank you for the change, is almost done. I've tested and worked in the Request, Request Rejected but still is a problem with the approver in Request accepted. 

![image](https://user-images.githubusercontent.com/26604752/27145352-bc420d72-50f2-11e7-869f-fbfc753d5190.png)

**Comment by amma35** [comment]
Can you retry the test by replacing the file again?

**Comment by George2x** [comment]
It works !, thank for your attention and support in the resolution.
