### ISSUE TITLE
[1.3.0] Error after valideted

### ISSUE THREAD

**Issue by AircraftRu** [InfotelGLPI/consumables#16]
Hello,
Plugin consumables 1.3.0
GLPI 9.1.4 and 9.2.1

Why the error?

![glpi - consumables wizard - google chrome 2017-12-11 15 20 18](https://user-images.githubusercontent.com/17082164/33830912-1885de8e-de87-11e7-9935-8ff830cbdb1f.png)

**Comment by amma35** [comment]
Fixed in https://github.com/InfotelGLPI/consumables/issues/12
