### ISSUE TITLE
kart limits

### ISSUE THREAD

**Issue by Etrange** [InfotelGLPI/consumables#17]
- The version of the plugin : 1.3.0
- The version of your GLPI : 9.2.1
- The steps to reproduce your issue :
2 products available in the stock (ECR01 and DEC01, in this example)
go to "consumable request" form
As super-admin profile, in the root entity:
1) add a product to the kart, with a big number (>11) of items (ref: ECR01 x 12)
2) select next product: it will show "no consumable" as availability (ref: DEC01). But this product is available in the stock.
It is impossible to add a second product.

Do the things the other way :
0) empty the kart
1) Add the second product first (DEC01) : availability list shows the right number, and choose "1", for instance
2) Add the second product (ECR01) select the number you want and add it to your kart (x250, if you want)
=> ok. Kart is complete and can be sent.
Why ??

It seems that there is a limit in the kart.
Sometimes it is the number of items, sometimes the number of products (1 product = 1 line in the kart)
I don't see any logic here.
So is there a bug ?

**Comment by Etrange** [comment]
Any idea ?

**Comment by amma35** [comment]
Yes, it's a bug, I have reproduced your problem very well.

**Comment by Etrange** [comment]
Hello,

In which version will the change be commit?
