### ISSUE TITLE
Mail not sent after request the item or if the item was refused.

### ISSUE THREAD

**Issue by LordBat** [InfotelGLPI/consumables#19]
Hi, this is very strange.

* Version of the plugin :      1.2.2

* Version of your GLPI :     9.1.4

* Steps to reproduce (which actions have you made) :
I setup the notification action by mail (Consumable Request and Consumable Request Validation).

* Expected result :
Mail sent to the requester and approver when the user request a consumable item.

Mail sent to the requester when the item has been refused or approved.

* Actual result :
Mail not sent. (Only works the Approved Item, Item requested or item refused not works)

* I cant find nothing about errors, php, mail, cron or events in glpi log folders.

Regards!

**Comment by Etrange** [comment]
Hi,

Did you get no mails or empty mails ?

Regards,

**Comment by LordBat** [comment]
Hi! i get no mails, and any type of error on logs.

I only could get 1 mail (Consumable Approved sended to the requester user). 

But mail notification about consumable requested ( i choose Requester and Approver users to send) or notification about Request Refused (Consumable Validation) are not send it.

Regards!

**Comment by amma35** [comment]
Hi,
Many corrections have been made since version 1.4.2.
We should test with this version.
We have just checked the notifications are being sent.
