### ISSUE TITLE
Direct access to consumables request

### ISSUE THREAD

**Issue by ERFPP** [InfotelGLPI/consumables#23]
* Version of the plugin :  1.5.0

* Version of your GLPI : 9.4.5

* Steps to reproduce (which actions have you made) : I want to share a consumable request link to users. When they open it, the page is empty because authentication is not done. We use SSO
http://--serveur--/glpi/plugins/consumables/front/wizard.form.php?action=consumablerequest

* Expected result :
For this to work they must first open GLPI. Authentication is done correctly in SSO, then they can click again on the links.

* Actual result :
The page is empty, no error.

* URL of the page :
http://--serveur--/glpi/plugins/consumables/front/wizard.form.php?action=consumablerequest
don't work
but if i want to share a new ticket page, the SSO work:
http://--serveur--/glpi/front/ticket.form.php

* Screenshot of the problem (if pertinent) :
![glpi](https://user-images.githubusercontent.com/67368034/85534873-fd625280-b611-11ea-9d16-9099348ddcb9.JPG)

**Comment by tsmr** [comment]
It's not possible sorry
