### ISSUE TITLE
SQL error on consumable request.

### ISSUE THREAD

**Issue by fcruz94** [InfotelGLPI/consumables#25]
* Version of the plugin : 1.6.0

* Version of your GLPI : 9.5.0

* Steps to reproduce (which actions have you made) : just make a consumable request

* Expected result : get a new request to validate.

* Actual result : nothing but an sql error in sql-errors.log. There is no consumable for validation and no record on database.

* URL of the page : it's not accesible from internet

* Screenshot of the problem (if pertinent) : these are the lines from sql-errors.log file:

`[2021-03-16 13:26:48] glpisqllog.ERROR: DBmysql::query() in /var/www/html/glpi/inc/dbmysql.class.php line 305

  *** MySQL query error:

  SQL: INSERT INTO `glpi_plugin_consumables_requests` (`consumableitemtypes_id`, `consumables_id`, `number`, `date_mod`, `give_items_id`, `give_itemtype`, `validators_id`, `status`, `requesters_id`) VALUES ('1', '2', '1', '2021-03-16 13:26:48', NULL, 'Group', '0', '2', '2')

  Error: Column 'give_items_id' cannot be null

  Backtrace :
  inc/dbmysql.class.php:1125                         
  inc/commondbtm.class.php:602                       DBmysql->insert()
  inc/commondbtm.class.php:1139                      CommonDBTM->addToDB()
  plugins/consumables/inc/request.class.php:788      CommonDBTM->add()
  plugins/consumables/ajax/request.php:45            PluginConsumablesRequest->addConsumables()`

**Comment by tsmr** [comment]
Old error / I close
