### ISSUE TITLE
Notification vides

### ISSUE THREAD

**Issue by jcovillers78114** [InfotelGLPI/consumables#30]
Dear GLPi user.

BEFORE SUBMITTING YOUR ISSUE, please make sure to read and follow these steps :

* Verify that your question has not already been asked
* Please use the below template.
* Delete this text before submiting your issue.

The Plugin team.

------------
* Version of the plugin : 
2.01

* Version of your GLPI : 
10.0.6

Bonjour,
Je reçois bien le mail de notification lorsqu'une demande de consommable est faite mais il est vide.
Les modèles de notifications sont complets et activés. Les balises sont renseignées ainsi que la langue correspondant au profil.

**Comment by glionel** [comment]
Je confirme.

Le plugin est intéressant, simple, malheureusement bourré d'incohérance. ça donne une impression de plugin non terminé. 
Et aucun support, ils ne répond jamais.

Notification vide, la liste de TOUT les demandeurs dans Validation est visible en Self-Service. C'est pas logique. L'utilisateur devrait voir seulement ces demandes et non ceux des autres. Bien que on ne peut pas voir le détail.

Du coup, je me suis tourné vers un formulaire. Une valeur sur.
