### ISSUE TITLE
Expression #1 of ORDER BY contains aggregate function and applies to the result of a non-aggregated query

### ISSUE THREAD

**Issue by FelipeBasilio1991** [InfotelGLPI/consumables#37]
Dear GLPi user.

BEFORE SUBMITTING YOUR ISSUE, please make sure to read and follow these steps :

* Verify that your question has not already been asked
* Please use the below template.
* Delete this text before submiting your issue.

The Plugin team.

------------
* Version of the plugin : 
2.0.1

* Version of your GLPI : 
11.0

* Steps to reproduce (which actions have you made) :
Validate an consumable

* Expected result :

* Actual result :
Expression #1 of ORDER BY contains aggregate function and applies to the result of a non-aggregated query

* URL of the page :

* Screenshot of the problem (if pertinent) :
<img width="839" alt="Capture" src="https://github.com/InfotelGLPI/consumables/assets/63825747/a2f5a8d6-21f8-4190-a2ef-813928ee2368">

**Comment by everaldovds** [comment]
I'm getting the same error

Version of the plugin :
2.0.1

Version of your GLPI :
GLPI 10.0.14 ( => /usr/share/glpi)
Installation mode: RPM

Steps to reproduce (which actions have you made) :
Validate an consumable

Expected result :

Actual result :
Expression #1 of ORDER BY contains aggregate function and applies to the result of a non-aggregated query

URL of the page :

Screenshot of the problem (if pertinent) :

![image](https://github.com/InfotelGLPI/consumables/assets/56073947/b9af7df9-cba7-4663-a1cf-a3d7146e6d19)

**Comment by Aissa92150** [comment]
Hello 

I'm getting the same error, 

Version of the plugin :
2.0.1

Version of your GLPI :
GLPI 10.0.14 ( => /usr/share/glpi)
Installation mode: RPM

Steps to reproduce (which actions have you made) :
Validate an consumable

Expected result :

Actual result :
Expression https://github.com/InfotelGLPI/consumables/issues/1 of ORDER BY contains aggregate function and applies to the result of a non-aggregated query

![glpi](https://github.com/InfotelGLPI/consumables/assets/171322946/a2b2bd1a-1e48-44c9-b9ed-95823f9f40e9)
![glpi 2](https://github.com/InfotelGLPI/consumables/assets/171322946/d263099b-2335-46de-ab7f-65acca98f881)

**Comment by tsmr** [comment]
Cannot reproduce with 10.0.17 version of GLPI
I close
