### ISSUE TITLE
consumables configuration

### ISSUE THREAD

**Issue by aldiop** [InfotelGLPI/consumables#7]
Hi
Please can you help me to configure this plugin , I want to set an user who will validate the requests, and an user who will receive  alerts of consumables status ?
Thanks

**Comment by amma35** [comment]
The configuration of the rights for the validation of consumable validation is done according to the profile.
So you need a profile that should have the right to read and consumable validation : 

![image](https://cloud.githubusercontent.com/assets/15138371/21712048/b39318e2-d3f2-11e6-921a-09276b36d4c1.png)

Then for alerts, this is configured in the recipients of the notifications concerned by the plugin.
You can add either a profile, a group, group managers ...
![image](https://cloud.githubusercontent.com/assets/15138371/21712177/6486b230-d3f3-11e6-80b8-e8d4c5bdb2ce.png)
